sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '9'
  - '10'
  - "lts/*"

after_success:
  - npm run report
  - npm run codecov

# Based on https://tailordev.fr/blog/2018/03/15/automated-npm-releases-with-travis-ci/
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: npm version --allow-same-version --git-tag-version false $TRAVIS_TAG
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true